services:

  # Collects KG files and ontologies
  # populates the volume load by SPARQL endpoint
  kg-harvester:
    build: ./kg-harvester
    volumes:
      - polifonia-kg:/data/
    container_name: polifonia-kg-harvester

  # SPARQL Endpoint service
  sparql:
    image: askomics/virtuoso
    ports: 
      - "${POLIFONIA_SP_ENDP_PORT-8891}:8890"
    volumes:
      - polifonia-kg:/data
    depends_on:
      - "kg-harvester"    
    container_name: polifonia-kg-sparql-endpoint
    environment:
      - DBA_PASSWORD=${POLIFONIA_SP_ENDP_PWD-password}

volumes:

  # Volume with KG data
  # - populated by kg-harvester
  # - load by sparql

  polifonia-kg:
